R/encoding.R

object 'n' not found in `read_lines_raw_()`

Fixed bug in guess_encoding

---

vignettes/locales.Rmd

Not saying that dplyr isn't smart :)

Write dplyr when it is readr

---

R/write.R
man/write_delim.Rd

Fix documentation typo

---

NEWS.md
src/Collector.cpp
src/Collector.h
tests/testthat/test-parsing-datetime.R

Dates should be based on doubles rather than integers

---

NEWS.md
src/DateTimeParser.h
tests/testthat/test-parsing-datetime.R

Support %I for 12 hour times

---

NEWS.md
src/SourceRaw.h
src/SourceString.h
src/read.cpp
tests/testthat/test-read-lines.R

Fixes #309, #403
I commented out the tests as they are pretty slow to run.

Support reading into long vectors

---

vignettes/column-types.Rmd

also a small typo (missing bracket)

add `.default` to the column vignette.

---

NEWS.md
R/col_types.R
tests/testthat/test-read-csv.R

Convert named lists to col_specs properly

---

NEWS.md
R/RcppExports.R
R/input.R
src/RcppExports.cpp
src/read.cpp
tests/testthat/test-read-file.R

Add read_file_raw() function

---

NEWS.md
R/read_fwf.R
R/source.R
R/utils.R
tests/testthat/test-read-fwf.R

read_fwf() on an empty file returns an empty tibble

---

R/col_types.R
R/read_delim.R

This makes them possible to suppress using `suppressMessages()`.

Specs now printed as a message in read_delim

---

R/col_types.R
R/read_delim.R
R/read_fwf.R
R/type_convert.R
tests/testthat/test-col-spec.R

Print column specifications from read_fwf and type_convert as well

---

NEWS.md
R/read_delim.R
R/tokenizer.R
man/Tokenizers.Rd
man/read_delim.Rd
man/spec_delim.Rd
src/Tokenizer.cpp
src/TokenizerDelim.cpp
src/TokenizerDelim.h
tests/testthat/test-tokenizer-delim.R

quoted_na argument to control behavior of missing values inside strings

---

vignettes/column-types.Rmd

Missing parenteses

---

R/col_types.R
tests/testthat/test-col-spec.R

Fix edge case in printing additional columns

---

NEWS.md
R/RcppExports.R
R/read_lines.R
R/tokenizer.R
man/Tokenizers.Rd
man/read_lines.Rd
src/RcppExports.cpp
src/Tokenizer.cpp
src/TokenizerLine.h
src/read.cpp
tests/testthat/test-read-lines.R
tests/testthat/test-write-lines.R

Add an na argument to read_lines()

---

src/Collector.cpp
src/Collector.h
src/Progress.h
src/Reader.cpp
src/Reader.h
src/TokenizerLine.h
src/grisu3.h
src/read.cpp

First pass at this is now working.
I may write a couple more constructors for the Reader class, so you don't have to do as much object instantiation up front.
It should be pretty straightforward to write chunked functions using this as well.

Refactor read functions

---

NEWS.md
R/read_fwf.R
R/read_table.R

Documents and "fixes" [issue #518](https://github.com/tidyverse/readr/issues/518).

add ability to tweak number of lines read for read_table

---

src/Collector.cpp
tests/testthat/test-parsing-logical.R

I tried implementing a case insensitive comparison but it was beyond me. True / False should get us most of the way there.

Support True False logical #514

---

NEWS.md
R/problems.R
R/read_delim.R
R/read_fwf.R
tests/testthat/test-problems.R

Issue #573 affected both the fixed-width and delimited files.  Tests are included for both, no exported functions were modified.

Fix and Tests for Issue #573

---

NEWS.md
R/col_types.R
R/utils.R
tests/testthat/test-col-spec.R

Print long spec declarations properly

---

NEWS.md
R/problems.R
R/read_delim.R
R/read_fwf.R
tests/testthat/test-problems.R

Output filename in problems

---

NEWS.md
src/QiParsers.h
tests/testthat/test-parsing-numeric.R

Return full string if no numbers passed to numeric parser

---

NEWS.md
src/Reader.cpp

Use tibble::as.tibble to construct tibbles

---

NEWS.md
R/collectors.R
man/parse_factor.Rd
src/Collector.cpp
src/Collector.h
tests/testthat/helper.R
tests/testthat/test-col-spec.R
tests/testthat/test-parsing-factors.R

This includes the changes in https://github.com/tidyverse/readr/pull/602, https://github.com/tidyverse/readr/pull/592 as well as the fix for https://github.com/tidyverse/readr/issues/615.

Improvements to factor parsing

---

NEWS.md
src/CollectorGuess.cpp
tests/testthat/test-col-spec.R
tests/testthat/test-collectors.R
tests/testthat/test-parsing-datetime.R
tests/testthat/test-parsing-numeric.R
tests/testthat/test-read-csv.R

Do not guess integer types when guessing columns

---

R/read_fwf.R

I was having trouble with this sentence structure..

Clarify `fwf_cols()` docs

---

R/write.R

Format datetimes in a format excel can parse

---

R/col_types.R

Demonstrate use of multiple column lists per issue 774.

Added additional example to cols

---

README.Rmd

fixes typo

---

README.Rmd
README.md

Add cheatsheet thumbnail to README

---

README.Rmd
README.md

As discussed in https://github.com/tidyverse/readr/pull/846#issuecomment-388237538.

Link cheatsheet directly to raw PDF

---

.Rbuildignore
.github/move.yml

* Add move bot configuration file.
* Add \.github to .Rbuildignore.

Add move-issues bot 🤖

---

R/write.R
man/write_delim.Rd

This fixes #849 
Please let me know if you have any feedback

Expand on mention of compressed formats

---

docs/reference/index.html

added missing parentheses to the reference website

---

.gitignore

Just gitignore all .o and .so files

---

_pkgdown.yml

Remove leading slash for article link

---

vignettes/readr.Rmd

Currently, I believe there is an issue with the formatting of the overview vignette
https://readr.tidyverse.org/articles/readr.html#available-column-specifications
This PR is just about trying to improve the formatting.

improve formatting at the end of the vignette

---

README.Rmd
README.md

Changed cheatsheet hosting link and recompiled README.Rmd

---

DESCRIPTION
src/TokenizerFwf.cpp

Suggest dplyr

---

.Rbuildignore
.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
README.Rmd
README.md

Fixes #1066
@jimhester please add `DEPLOY_PAT` to repo secrets

add github actions

---

.github/workflows/pkgdown.yaml

Adding in tidy template for pkgdown
@jimhester

add tidy template

---

NEWS.md
src/Source.cpp

Fix initialization issues in Source::skipLines()

---

R/source.R

update documentation to reflect change to `read_delim` API

---

NEWS.md
R/cpp11.R
R/type_convert.R
man/type_convert.Rd
tests/testthat/test-type-convert.R

Include guess_integer argument in type_convert

---

tests/testthat/_snaps/col-spec.md
tests/testthat/_snaps/edition-1/col-spec.md
tests/testthat/_snaps/edition-1/read-csv.md
tests/testthat/_snaps/edition-2/col-spec.md
tests/testthat/helper.R
tests/testthat/setup.R
tests/testthat/test-col-spec.R

Use testthat 3e features more

---

NEWS.md
R/utils.R
man/show_progress.Rd

Use `rlang::is_interactive()`

---

src/Progress.h

I believe the fill constructor (6) is intended here:
https://www.cplusplus.com/reference/string/string/string/

switch argument order in std::string()

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
.github/workflows/pr-commands.yaml
.github/workflows/test-coverage.yaml
DESCRIPTION
_pkgdown.yml

Update pkgdown site

---

DESCRIPTION

Part of #1372 
But I think this is the last upkeep item!

bump minimum R version

---

R/problems.R
man/problems.Rd

And wrap on one line (75 chars)

Fix typo (An -> A Dataframe)

---

vignettes/locales.Rmd

Bring back the encoding example
