R/parsers.R, inst/include/fastread/Source.h, inst/include/fastread/VectorInput.h, inst/include/fastread/get_int_naive.h
Main:
* Trimming was optional in character_parser() but actually not implemented.
Additionally:
* change integer parsing from 0 to -1 for unrecognised integers;
* count lines correctly if last line of file has no '\n' line break, which happens to some CSV files.
=> Implement character trimming

R/read_delim.R
"inline" and "in line" are different things. Also, expand on the 'delim' description to give some examples (I expect anyone who uses fastread to know what a delimiter is, but I pray for a day when fastread or something like it is just SOP and something new users are exposed to. In the meantime, example-driven docs cost nothing).
=> Doc tweaks

R/read_delim.R
In `read_csv2`, I think `delim` parameters should be `;` instead of `.`.
Thanks again for this wonderful package
=> Typo in read_csv2

R/read_delim.R
read_csv2 uses ";" as separator
=> Typo in read_delim documentation

src/CollectorInteger.h
I think this should cause the proper warning when integers fail to parse.
With the usual caveats:
=> Give the appropriate warning for integers.

DESCRIPTION
Adds a BugReports link to the DESCRIPTION file so that CRAN-sourcing users can find the repo easily if they run into problems or have patches.
=> Add github link to DESCRIPTION

NEWS.md, R/read_delim.R, R/read_fwf.R, R/tokenizer.R, man/Tokenizers.Rd, man/read_delim.Rd, man/read_fwf.Rd, man/read_table.Rd, src/Token.h, src/Tokenizer.cpp, src/TokenizerDelim.h, src/TokenizerFwf.h, src/TokenizerLog.h, tests/testthat/test-read-csv.R, tests/testthat/test-read-fwf.R
Addresses #125 and #114.
I tried to follow the conventions of `utils::read.table`, namely `na = NULL` indicates no missing values while `na = ""` indicates that empty strings should be interpreted as missing values:
```r
example = "a,b
1,foo
,
"
f = textConnection(example)
read.csv(f, colClasses = c(a = "integer", b = "character"), na.strings = NULL)
#>    a   b
#> 1  1 foo
#> 2 NA    
close(f)
f = textConnection(example)
read.csv(f, colClasses = c(a = "integer", b = "character"), na.strings = "")
#>    a    b
#> 1  1  foo
#> 2 NA <NA>
close(f)
```
The implementation of `Token::flagNA` is a simple loop, I'm happy to do a performance comparison with less naive implementations if the behaviour is correct (although I suspect that the simple loop will win for small numbers of `na` strings).
=> Allow multiple strings for missing values and correctly treat na = ""

R/write.R, man/write_delim.Rd
Modified documentation for the `append` param for the `write_*` functions to make it clear that if a file does not previously exist a new file is created.
This is to address / fix #181 .
=> clarify write_* docs (append param).

NEWS.md, R/col_types.R
=> don't stop() if there are unmatched column types

NEWS.md, src/CollectorDate.h, src/CollectorDateTime.h, src/DateTimeParser.h, tests/testthat/test-datetime.R
partial ISO8601 date time format.
=> Fix a bug in DateTimeParser where compound formats would get parsed as

NEWS.md, src/DateTime.h, tests/testthat/test-datetime.R
Note that this patch does *not* provide unambiguous nor even deterministic parsing of local times for the two hours that overlap at the end of daylight savings, as a consequence of the return value of `mktime()` being undefined for those two hours.
Perhaps the user should be warned/the return value should be fixed when parsing those two problem hours, but it's not clear how best to implement such behaviour.
=> Fix daylight savings bug for unambiguous times. Closes #120

NEWS.md, R/read_fwf.R
There was an unintentional double negotation when checking on the number of columns.
(this is my first pull request, so I don't know if I follow the right procedure here by doing it like this)
=> Fixed bug in fwf_empty

R/read_delim.R, man/read_delim.Rd, man/read_fwf.Rd, man/read_log.Rd, man/read_table.Rd, man/type_convert.Rd
Documentation now informs the user that "**D**"ate is a valid column type when using `col_types` in `read_delim()`, etc.
=> Augments documentation

NEWS.md, src/Collector.cpp, tests/testthat/test-parsing-logical.R
It is not uncommon that boolean values are noted as `0`/`1` or lowercase `true`/`false` in csv.
=> Allow for lowercase and 0/1 logical values

R/type_convert.R, tests/testthat/test-type-convert.R, tests/testthat/test-write-delim.R
Otherwise, when input is character, the function makes it impressively far before failing with a cryptic message:
``` r
library(readr)
not_df <- matrix(letters[1:12], nrow = 4,
dimnames = list(NULL, paste0("V", 1:3)))
type_convert(not_df)
#> Error: `col_names` must be TRUE, FALSE or a character vector
type_convert(not_df, col_names = TRUE)
#> Error in type_convert(not_df, col_names = TRUE): unused argument (col_names = TRUE)
```
Of course it would also be pretty sweet if `type_convert()` accepted a character matrix as input.
=> Require data.frame input for type_convert()

NEWS.md, R/col_types.R, tests/testthat/test-col-spec.R
Before:
``` r
library(readr)
(x <- read_csv("1,2,3,4\n", c("a", "b"), "iiii"))
#> Warning: Insufficient `col_names`. Adding 2 names.
#>   a b X4 X5
#> 1 1 2  3  4
(x <- read_csv("1,2,3\n", "a", "c_c"))
#> Warning: Insufficient `col_names`. Adding 1 names.
#>   a NA
#> 1 1  3
```
After:
```r
load_all(".")
(x <- read_csv("1,2,3,4\n", c("a", "b"), "iiii"))
#> Warning: Insufficient `col_names`. Adding 2 names.
#>   a b X3 X4
#> 1 1 2  3  4
(x <- read_csv("1,2,3\n", "a", "c_c"))
#> Warning: Insufficient `col_names`. Adding 1 names.
#>   a X2
#> 1 1  3
```
=> Fix addition of column names; fixes #373

NEWS.md, R/collectors.R, src/DateTime.h, src/DateTimeParser.h, tests/testthat/test-parsing-datetime.R
Support parsing a year-only e.g. `%Y` format:
```r
read_csv("x,y\n2014,2014\n", col_types = list(col_date("%Y"), col_datetime("%Y")))
```
It's a bit of an edge case, but if the user specifically sets the format to `%Y` this should work.
=> Support parsing year only dates

NEWS.md, R/read_fwf.R, src/TokenizerFwf.cpp, src/TokenizerFwf.h, tests/testthat/test-read-fwf.R
This pull request should fix items 300 and 326. The current fwf format is kind of broken if you want to read a subset of columns.
Ragged fwf (where the last column width if variable) do exists, but they should be a minority. This implementation assumes ragged fwf only when the last end position is NA, Inf or omitted.
```R
x <- '12345A\n67890BBBBBBBBB\n54321C'
col_names <- c('A','B','C')
start <- c(1,3,6)
end   <- c(2,5,6)
col_positions <- fwf_positions(start,end,col_names)
df1 <- read_fwf(x,col_positions = col_positions);df1
col_positions <- fwf_positions(start[1:2],end[1:2],col_names[1:2])
df2 <- read_fwf(x,col_positions = col_positions);df2
col_positions <- fwf_positions(start,end[1:2],col_names)
df3 <- read_fwf(x,col_positions = col_positions);df3
col_positions <- …
```
=> Fixing of ragged fixed width format files and reading a subset of columns

NEWS.md, R/col_types.R, tests/testthat/test-col-spec.R
The skip line was being used even if `col_names = FALSE`, skipping only when `TRUE` fixes the issue.
Fixes #333
=> Only skip the first line if data includes col_names

NEWS.md, src/QiParsers.h, tests/testthat/test-parsing-numeric.R
Explicitly checking for this case seems like the best option. I played around with editing the DFA in parseNumber but it ended up being more hassle than it was worth.
Fixes #297
=> single '-' or '.' are now parsed as characters rather than numeric

NEWS.md, src/QiParsers.h, tests/testthat/test-parsing-numeric.R
=> Properly guess type for numbers with a trailing character

NEWS.md, R/collectors.R, man/parse_datetime.Rd, man/parse_vector.Rd, tests/testthat/test-parsing-datetime.R, tests/testthat/test-parsing-time.R
All of the other parse_* functions already had an na argument they were passing to parse_vector.
Fixes #413
=> Add na arguments to parse_date() parse_time() and parse_datetime()

NEWS.md, src/QiParsers.h, tests/testthat/test-parsing-numeric.R
=> Parsing negative numbers now returns negative values

NEWS.md, src/CollectorGuess.cpp, src/DateTimeParser.h, tests/testthat/test-parsing-time.R
One thing to note with this is the default time format is `%H:%M`, so the examples in the issue are still going to be guessed as dates unless they change the `time_format` in the locale (as is done in the tests).
I don't know if we should change the default time format to `%H:%M:%S` or not.
Fixes #384
=> collector_guess now guesses time formats as well

NEWS.md, R/read_fwf.R
This is a really simple change that allows someone to specify negative column widths when using `read_fwf()`. To demonstrate the problem here's a comparison of `read.fwf()` versus `read_fwf()` when one wants to skip a column:
```
> read.fwf(fwf_sample, widths = c(5, -1, 4), col.names = letters[c(1,3)])
a    c
1 12345 7890
2 12345 7890
3 12345 7890
4 12345 7890
5 12345 7890
> read_fwf(fwf_sample, fwf_widths(c(5, -1, 4), letters[1:3]), col_types = cols(a = "i", b = "_", c = "i"))
Error: Begin offset (5) must be smaller than end offset (4)
```
If a user is porting code from `read.fwf()` to readr, they are very likely to have negative column widths. This PR simply converts width to positive values as required by `fwf_widths()`, such that the result of the above is:
```
> read_fwf(fwf_sample, …
```
=> Convert negative fwf widths to positive

DESCRIPTION, NEWS.md, R/write.R, src/RcppExports.cpp, src/grisu3.c, src/grisu3.h, src/write_delim.cpp
The previous implementation as we know was very slow because of the character conversion, on par with `write.csv()`.
```r
set.seed(1)
df <- as.data.frame(matrix(runif(256*2^15), nrow = 256))
system.time(write.csv(df, "/tmp/df1.csv"))
#>    user  system elapsed 
#>  26.074   7.622  33.776
system.time(readr::write_csv(df, "/tmp/df4.csv"))
#>    user  system elapsed 
#>  34.012   0.537  34.589
```
https://github.com/hadley/readr/commit/9c286458d1797b00a0212c3fe374a9841d606c12 just does a little cleanup and turns off converting numeric to character first. This produces valid round trip-able results and is quite a bit faster than converting to character, however all numeric numbers are printed with the maximum amount of precision.
```r
system.time(readr::write_csv(df, "/tmp/df4.csv"))
#> …
```
=> write_* improvements

NEWS.md, R/type_convert.R, man/type_convert.Rd, tests/testthat/test-type-convert.R
Another alternative would be to subset the col_types with the is_character logical vector as is already done for the data.frame and col_names. Not sure which way would be more useful to people.
e.g. a diff from this PR
```diff
diff --git a/R/type_convert.R b/R/type_convert.R
index 3a46932..bbd5c6c 100644
--- a/R/type_convert.R
+++ b/R/type_convert.R
@@ -44,8 +44,7 @@ type_convert <- function(df, col_types = NULL, na = c("", "NA"), trim_ws = TRUE,
})
if (is.character(col_types)) {
-    stop("`col_types` must be `NULL` or a `cols` specification for `type_convert()`.",
-      call. = FALSE)
+    col_types <- paste(collapse = "", substring(col_types, which(is_character), which(is_character)))
}
col_types <- col_spec_standardise(
```
Fixes #369
=> type_covert now accepts only NULL or a cols specification for col_types

NEWS.md, R/input.R, R/read_delim.R, R/read_lines.R, R/utils.R, src/SourceFile.h, tests/testthat/test-read-csv.R, tests/testthat/test-read-file.R, tests/testthat/test-read-lines.R
I did the file tests in the R side as I didn't think it was worth pulling in the needed Boost headers to do the equivalent test for an empty file.
Fixes #356
=> Return empty objects rather than signaling an error on an empty file.

NEWS.md, R/locale.R
Fixes #416 
This seemed a more light weight solution than actually using the memoise package. Because subsequent calls will have the option set I had to remove the message as it was no longer informative or accurate.
=> save results from default_locale

NEWS.md, R/col_types.R, tests/testthat/test-read-csv.R
The result is now what I expect, but seems like there should be problems? I don't know how to fix that.
``` r
(too_many <- read_csv("v1,v2\n1,2", col_types = "iii"))
#> Warning: Unnamed `col_types` should have the same length as `col_names`.
#> Using smaller of the two.
#>   v1 v2
#> 1  1  2
problems(too_many)
#> [1] row      col      expected actual  
#> <0 rows> (or 0-length row.names)
```
=> Subset col_types when there are too many; fixes #371

NEWS.md, src/QiParsers.h, tests/testthat/test-parsing-numeric.R
This works around an unaddressed spirit regression
(https://svn.boost.org/trac/boost/ticket/11608).
Fixes #412 
I did some benchmarks and there was no performance regressions when parsing a large file of doubles.
Note the numbers being tested are both representable as regular doubles, the `double_` parser is just parsing them improperly.
=> Parse doubles with boost::spirit::qi::long_double

NEWS.md, src/Source.h, src/SourceFile.h, src/SourceRaw.h, src/SourceString.h, tests/testthat/test-parsing-character.R
This works for the test case, the main issue is it really only needs to check for this at the beginning of the file (if it is a UTF-8 file). I am still trying to figure out the best place to put this logic, suggestions welcome!
Fixes #263
=> Check for BOM when converting

NEWS.md, R/collectors.R, R/locale.R, man/locale.Rd, man/parse_datetime.Rd, src/Collector.cpp, src/CollectorGuess.cpp, src/DateTimeParser.h, tests/testthat/test-col-spec.R, tests/testthat/test-parsing-datetime.R
Need to either consistently use flexible parser, or format specified in locale
or provide someway to select between them
=> Make defaults consistent

NEWS.md, src/grisu3.c, tests/testthat/test-write-delim.R
This ensures they will be read as decimals in the future.
If we want to go this route the implementation was not too hard to do.
Fixes #482
=> Always print .0 after whole number decimals

R/col_types.R, R/utils.R, tests/testthat/test-col-spec.R
=> Handle printing of non-syntactic names in col specs

DESCRIPTION
write_delim.cpp uses vector.at() which was added in RCPP 0.12.0.5.
See change log for https://github.com/RcppCore/Rcpp/commit/e4868b8f3918dc2f9633c25d8169b53b0a22d1ad
=> Update RCPP Dependency

NEWS.md, R/read_delim.R, tests/testthat/test-read-csv.R
A message is provided if the locale is updated automatically by read_csv2(); if the caller passes an explict locale, it is not updated.
=> read_csv2() locale issues

NEWS.md, src/read.cpp, tests/testthat/test-read-chunked.R
Previously we were 'checking' the SEXP address, which would always be
non-zero. This meant that there was no value returned by callback that
would halt the reading.
Instead we need to explicitly test the value of the first element of the logical vector.
I unfortunately realized this this morning instead of yesterday, unfortunate timing considering we released yesterday 😞 .
=> Properly allow stopping of chunked reading

R/collectors.R
Support for `%I` in `parse_datetime` was added in https://github.com/tidyverse/readr/pull/426, but this was not documented. This PR documents this format, recommending using it with AM/PM.
=> Document %I format, recommend for use with AM/PM

NEWS.md, src/TokenizerFwf.cpp, tests/testthat/test-read-fwf.R
=> Raise error on zero-length specifications for FWF tokenizer

R/lines.R, R/read_delim.R, R/read_fwf.R, R/read_lines_chunked.R, R/read_log.R, R/read_table.R, R/utils.R, R/zzz.R
Change defaults for displaying the progress bar to be similar to those for dplyr. Currently, the progress bar defaults to display when not interactive. However, it will still display in knitr documents if they are compiled in an interactive session.
This patch defines an unexported function `progress_defaults` which sets checks for an option `readr.show_progress`, whether it is interactive, and whether it is in a knitr document (`knitr.in.progress`). This is equivalent to how `dplyr` defaults for showing a progress bar.
=> change progress defaults

NEWS.md, src/DateTimeParser.h, tests/testthat/test-parsing-time.R
=> `parse_time()` now correctly handles 12 AM/PM

NEWS.md, R/read_table.R, src/TokenizerFwf.cpp, tests/testthat/test-read-fwf.R
=> `read_table()` can now handle files with many lines of leading comments

NEWS.md, src/grisu3.c, tests/testthat/test-write-delim.R
=> Whole number doubles are no longer written with a trailing `.0` decimal

NEWS.md, R/RcppExports.R, R/lines.R, man/read_lines.Rd, src/RcppExports.cpp, src/write.cpp, tests/testthat/test-write-lines.R
=> `write_lines()` now accepts a list of raw vectors

NEWS.md, R/read_table.R, R/source.R, tests/testthat/test-read-fwf.R
Fixes #552 
The `missing()` calls in https://github.com/tidyverse/readr/compare/552?expand=1#diff-7f0d4a03d8bda22664cf51f3fcf4a243R36 are a little gross, but we only want to override the current values if the first value is a data source _and_ non-default values are passed to the `datasource()` constructor.
=> Use a datasource for all file arguments in read_table

NEWS.md, R/col_types.R, R/read_delim.R, R/read_fwf.R, R/read_table.R, R/type_convert.R, R/utils.R, man/type_convert.Rd, tests/testthat/test-col-spec.R
Fixes #588 
I added another example showing how to read a dataset as character and using `type_convert()` to infer types based on the full dataset as well.
=> Better error handling for guess_max

DESCRIPTION, NEWS.md, R/RcppExports.R, R/file.R, R/lines.R, R/source.R, R/write.R, man/read_file.Rd, man/read_lines.Rd, man/write_delim.Rd, src/RcppExports.cpp, src/write.cpp, src/write_connection.cpp, src/write_connection.h, src/write_delim.cpp, tests/testthat/helper.R, tests/testthat/test-read-fwf.R, tests/testthat/test-write-delim.R, tests/testthat/test-write-lines.R
Fixes #348 
This still needs documentation, more tests and examples, but works pretty well.
The connection writing uses [boost::iostreams](http://www.boost.org/doc/libs/1_63_0/libs/iostreams/doc/), so is nicely buffered and should be pretty performant.
=> Writing to compressed files / connections

src/TokenizerDelim.cpp
Using a modulo power of 2 lets the compiler simplify the expression into
an and, which requires far fewer (and lest costly) instructions. This
also avoids the expression returning true for the entire row 10000. See
https://godbolt.org/g/N1TLPY for the generated assembly for each
alternative.
This gives us a fairly minor ~7%, but consistent execution increase over the
previous behavior.
Unit: seconds
expr      min       lq     mean   median       uq      max neval
current 2.145237 2.159644 2.231668 2.225491 2.259040 2.469164    10
simplified 1.967682 2.062774 2.075334 2.072157 2.097775 2.186902    10
=> Simplify the modulus expression

R/example.R, man/readr_example.Rd
I think it's nice to list the possible examples when `path` is unspecified. I also expected to see `readr_example()` in the help index. I think it's fine to remove the internal keyword, yes?
=> List files with readr_example() and remove internal keyword

R/read_delim.R, R/type_convert.R, README.Rmd, README.md, man/read_delim.Rd, man/read_delim_chunked.Rd, man/read_fwf.Rd, man/read_log.Rd, man/read_table.Rd, man/spec_delim.Rd, man/type_convert.Rd
I rebuilt the pkgdown site locally, but the diff was bigger than I was expecting, so I did not include that in this PR.
=> Remove references to the removed column-types vignettes

R/problems.R
Because tibble has a `format` method which behaves differently than
`format.data.frame` it broke the old printing code.
Fixes #685
=> Convert to a standard data frame before printing problems

NEWS.md, R/source.R
This is to allow files to be read via FTP over SSH.
=> Recognise sftp:: as a protocol for URLs

R/type_convert.R, man/type_convert.Rd
Documentation assumes that the guessing in `type_convert()` relies on the first 1,000 rows as elsewhere. However, this does not appear to be true:
```r
library(readr)
test <- tibble::tibble(x = c(1:10000, "a"))
class(type_convert(test)$x)
#> Parsed with column specification:
#> cols(
#>   x = col_character()
#> )
#> [1] "character"
````
=> Correct documentation for type_convert about guessing

R/read_delim.R
Fix a bug in `read_csv` where the argument `quoted_na` was not being used.
=> [Bug Fix] `quoted_na` was not being used by `read_csv`

R/date-symbols.R
`date_names_locales` has been replace by `date_names_langs` for some time now. 
I believe it is the last reference to it in the documentation.
=> Correct reference to date_names_langs

tests/testthat/test-read-fwf.R
As discussed in https://github.com/krlmlr/readr/commit/4d1021e7ab09a66bd432b25590603d7c7f6baf88#commitcomment-22129539. I've stripped the CRAN comments because they don't apply anymore, and the version number update. Thanks again for your help.
=> Don't test error message that is created by tibble

NEWS.md, R/RcppExports.R, R/lines.R, man/read_lines.Rd, src/RcppExports.cpp, src/write.cpp, tests/testthat/test-write-lines.R
=> `write_file()` gains a `sep` argument, to specify the line separator

R/col_types.R, man/cols.Rd
A missing # in the col_types example was causing "them like so:" to be executed as code and so the package checks to fail.
=> Fix missing # in example causing check to fail

R/tokenizer.R
Current wording says "Character vector of strings to use for missing values."  To me, this sounds like these will be INSERTED in place of missing values, so I changed the text to "to interpret as missing values". 
For what it's worth, read.csv uses 'na.strings', which is documented as "a character vector of strings which are to be interpreted as NA values".
Also, would it be worthwhile to caution the user that "NA" strings (North America, Sodium, etc) will be turned into missing values?
=> Tweak language for na parameter

R/read_fwf.R
the example rd file currently cuts off the names..  thanks
> # 3. Paired vectors of start and end positions
> read_fwf(fwf_sample, fwf_positions(c(1, 30), c(10, 42), c("name", "ssn")))
Parsed with column specification:
cols(
name = col_character(),
ssn = col_character()
)
name       ssn         
<chr>      <chr>       
1 John Smith 418-Y11-4111
2 Mary Hartf 319-Z19-4341
3 Evan Nolan 219-532-c301
> # 4. Named arguments with start and end positions
> read_fwf(fwf_sample, fwf_cols(name = c(1, 10), ssn = c(30, 42)))
Parsed with column specification:
cols(
name = col_character(),
ssn = col_character()
)
name       ssn         
<chr>      <chr>       
1 John Smith 418-Y11-4111
2 Mary Hartf 319-Z19-4341
3 Evan Nolan 219-532-c301
=> read_fwf .rd file name column ends at position 20, not 10

src/SourceFile.h
i.e. boost::interprocess::read_private instead of
boost::interprocess::read_only
Filesystems are much likely to support MAP_PRIVATE rather than
MAP_SHARED (e.g. FUSE).
=> Use private mapping (instead of shared) for SourceFile.

NEWS.md, R/collectors.R, man/parse_datetime.Rd, src/DateTimeParser.h, tests/testthat/test-parsing-datetime.R
To keep with other similar libraries, I've chosen `%a` as the designator. This might cause some issues when doing non-abbreviated day of week in future as `%A` is already reserved for other uses.
This PR updates the documentation, however none of the generated docs have been updated - is this something expected of contributors? If so, could you please tell me how to generate the documentation.
=> Add support for day of week in parse_datetime

NEWS.md, src/Source.cpp
fixes #834, fixes #837 
As described on #834, the behavior of `normalizePath()` (more precisely, `path.expand()`, which is used inside `normalizePath()`) has been changed to return the character encoded in UTF-8. I guess this happens only with Windows on non-UTF-8 locales.
R 3.4.4 on Windows 10:
``` r
Encoding(normalizePath("~/鬼"))
#> [1] "unknown"
```
R 3.5.0 on Windows 10:
``` r
Encoding(normalizePath("~/鬼"))
#> [1] "UTF-8"
```
This usually doesn't become a problem; on R codes, most R functions take care of the encoding automatically. But, on C++ codes, the encoding attribute is lost when the `String` is converted to `std::string`. So, we need to convert it to the proper encoding before passing it to the functions that take `std::string`, in this case, …
=> convert path to the native locale before passing to boost::interprocess::file_mapping()

DESCRIPTION, R/col_types.R, R/collectors.R, man/col_skip.Rd, man/cols.Rd, man/parse_atomic.Rd, man/parse_datetime.Rd, man/parse_factor.Rd, man/parse_guess.Rd, man/parse_number.Rd, man/parse_vector.Rd, man/spec.Rd
Fix #888
Following this, a general documentation update should be performed to bring all the documentation up to roxygen2 version 6.1.0 formatting.
=> Documentation update to clarify column abbreviations and link parsing help pages

README.Rmd, README.md
This would fix a mixed-content warning on https://readr.tidyverse.org/ However, note that there is still an old link to http://tidyverse.org/rstudio-logo.svg; I did not change those as they are in pkgdown-generated files. I assume that would be taken care of when the files are rebuilt.
(PS, can you also change the URL here on GitHub to https as well?)
=> Use https for badge links.

NEWS.md, R/RcppExports.R, R/melt_delim.R, R/read_delim.R, R/source.R, src/RcppExports.cpp, src/connection.cpp
Because we previously read connections into an in-memory vector we would
frequently run into out of memory issues when reading from a
connection.
We automatically cleanup the temporary file using a finalizer when the datasource object is removed.
=> Read connections to a temporary file rather than to a raw vector

NEWS.md, R/RcppExports.R, R/col_types.R, R/lines.R, R/melt_delim.R, R/read_delim.R, R/read_fwf.R, R/read_table.R, R/source.R, R/utils.R, R/zzz.R, man/datasource.Rd, man/read_lines.Rd, src/RcppExports.cpp, src/Source.cpp, src/Source.h, src/SourceFile.h, src/SourceRaw.h, src/SourceString.h, src/Tokenizer.cpp, src/TokenizerDelim.cpp, src/TokenizerLine.h, src/parse.cpp, src/read.cpp, tests/testthat/test-melt-csv.R, tests/testthat/test-read-csv.R, tests/testthat/test-read-lines.R, tests/testthat/test-write.R
We now always count empty lines and comments as part of the number of
skips, but also skip any remaining blank lines are comments after the
skips. This allows you to have consistent skip behavior but also makes
it easy to ignore blanks, which is useful with messy inputs.
Fixes #923
Fix test
=> Adds much more robust empty line and comment skipping

R/read_delim.R, man/read_delim.Rd, man/read_delim_chunked.Rd, man/read_fwf.Rd, man/read_log.Rd, man/read_table.Rd, man/spec_delim.Rd
Noted that `factor` was not part of the documentation to the `col_types` argument of `read_delim`, despite the fact that setting `col_types = "f"` yields a factor column. Hence suggesting an update of the documentation.
=> Updated documentation of col_types to include factors

NEWS.md, R/col_types.R, tests/testthat/colour-test, tests/testthat/helper.R, tests/testthat/test-col-spec.R
I think open questions are the colors to use and if we need a readr specific way to turn this off (right now it uses `crayon::has_color()`).
I used the following to test how it looks
```r
library(dplyr)
library(nycflights13)
library(readr)
set.seed(42)
flights %>%
transmute(
carrier, flight, tailnum, origin, dest,
departure = lubridate::make_datetime(year, month, day, hour, minute),
delayed = arr_delay > 15) %>%
sample_n(25) %>%
write_tsv("flights.tsv")
read_tsv("flights.tsv")
```
=> Colourise types of columns when printing specs

R/write.R, man/format_delim.Rd, man/write_delim.Rd
Implements changes suggested in #635 
Changes the examples so that they demonstrate write_*() behavior when you only specify a file name. Removes use of tempfile() and tempdir()
=> change examples to no longer use tempfiles

R/write.R, man/format_delim.Rd, man/write_delim.Rd
- changes format_delim() documentation so that it no longer inherits examples from write_delim()
- removes write_*() examples from format_*() docs and format_*() examples from write_*() docs
=> separate write_*() and format_*() examples

NEWS.md, R/read_delim.R
Add an early check if a `datasource_connection` results in an `empty_file` and just return an empty tibble if so.  Fixes tidyverse/readr#963
=> Add early check for connections with empty data

DESCRIPTION, man/readr-package.Rd
because `aut` was a bit much for my contribution to `readr`.
=> Romain becomes a ctb

NEWS.md, R/type_convert.R, man/type_convert.Rd, tests/testthat/test-type-convert.R
closes #1032
(I realize I'm bending the [acknowledgement style](https://style.tidyverse.org/news.html#acknowledgement) by including Jim in this bullet.  But it was his idea to remove the spec attribute, instead of update it.)
=> `type_convert()` removes a 'spec' attribute

vignettes/locales.Rmd
The locales vignette states that the argument `time_format` is not used for anything:
https://github.com/tidyverse/readr/blob/0384d8792d6efd961eb1c3c6cdd4df5888c93a4a/vignettes/locales.Rmd#L110
However as of readr [1.0.0](https://github.com/tidyverse/readr/blob/master/NEWS.md#readr-100), the `time_format` argument of `locale()` is used to guess the column type.
Furthermore, `local_time` can now be used to with `parse_time()`. Compare readr 1.3.1:
```
packageVersion("readr")
library(readr)
parse_time("01:02:03", locale = locale(time_format = "%H:%M:%S"))
parse_time("01:02:03", locale = locale(time_format = "%S:%M:%H"))
```
to 0.2.0:
```
packageVersion("readr")
library(readr)
parse_time("01:02:03", locale = locale(time_format = "%H:%M:%S"))
parse_time("01:02:03", locale = locale(time_format …
```
=> Document time_format in locales vignette.

vignettes/locales.Rmd
The locales vignette specifies the American date system as `"%d/%m/%Y"`, but the month should be first, i.e. `"%m/%d/%Y"`. In other words, in the American system 01/02/2013 is January 2nd, not February 1st.
https://github.com/tidyverse/readr/blob/0384d8792d6efd961eb1c3c6cdd4df5888c93a4a/vignettes/locales.Rmd#L120
The similar code in the test below has the correct order, so I assume the vignette is a typo:
https://github.com/tidyverse/readr/blob/05890c3b493458ad4699654ceed58d2515939e94/tests/testthat/test-parsing-datetime.R#L187
One suggestion to make the example less ambiguous would be to use a date such 01/31/2013, where it is clear that 31 must refer to the day (I'm happy to make that change to the vignette if you like).
I agree, the American date system is illogical!
=> Fix typo in example of illogical date system.

NEWS.md, R/write.R, tests/testthat/test-write.R
The write_*() functions were no longer returning the input 'x' invisibly as stated in the documentation, but rather similar data frames with factors and datetimes converted to character columns.
This PR fixes that, so that the invisible return value is identical to 'x'.
Fixes #975
=> write_*() functions again return identical data frame they were given

NEWS.md, R/source.R
This fixes #1050 by adding the `on.exit(close(con, add = TRUE))` before opening the connection as in other function like `write_file`
https://github.com/tidyverse/readr/blob/192cb1ca5c445e359f153d2259391e6d324fd0a2/R/file.R#L49-L58
=> add the close in on.exit before opening the connection

R/collectors.R, man/parse_number.Rd
=> Added new examples to parse_number

R/write.R, man/format_delim.Rd, man/write_delim.Rd
Backticks were skipped in documentation, so Rd file failed to parse
=> Add missing backticks.

vignettes/readr.Rmd
The previous text says "we don't guess that currencies are numbers, even though we can parse them", and then the example didn't try to parse a currency value.  The next text has "The" when it should have "There".
=> Minor errors in guess_parser docs.

R/file.R, R/lines.R, R/write.R, man/format_delim.Rd, man/read_file.Rd, man/read_lines.Rd, man/write_delim.Rd
Before, the documentation for param `x` in `write_delim()` inside `R/write.R` **was reused** for `write_file()`, `write_lines()` and `format_*()` – which is obviously wrong. This PR redefines/overwrites the param `x` documentation where appropriate.
=> Differentiate param `x`

R/read_delim.R
This PR simply adds one line to the documentation of `read_delim` in order to explain how to silence the `col_types` message that is printed out if the user does not provide a `cols()` specification.
Rationale:
- Some users do not need to see the "Parsed with column specification" messages that `readr` prints out when `col_types` is not defined by a user-provided `cols` object.
- Removing those messages is [easy in R Markdown](https://github.com/tidyverse/readr/issues/954), but not outside of it, unless the user adds `suppressMessages` calls everywhere in the code.
- Adding a `quiet` argument is far less elegant than [what @jimhester suggests](https://github.com/tidyverse/readr/issues/695): passing `col_types = cols()` (brilliant tip, thanks!).
This PR simply adds this tip to the end of …
=> Document how to silence `col_types` messages

R/read_fwf.R
`writeLines()` shows the example data in a more representative way than `cat()`
``` r
library(readr)
fwf_sample <- readr_example("fwf-sample.txt")
cat(read_lines(fwf_sample))
#> John Smith          WA        418-Y11-4111 Mary Hartford       CA        319-Z19-4341 Evan Nolan          IL        219-532-c301
writeLines(read_lines(fwf_sample))
#> John Smith          WA        418-Y11-4111
#> Mary Hartford       CA        319-Z19-4341
#> Evan Nolan          IL        219-532-c301
```
<sup>Created on 2019-10-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
=> Fix in examples of read_fwf: cat() → writeLines()

NEWS.md, R/read_delim.R, tests/testthat/test-read-csv.R
tibble::data_frame is now deprecated but was still used for empty datasource connections. I found no change to passing tests or documentation.
Fixes #1099
=> Update tibble::data_frame references to tibble::tibble

README.Rmd
I can imagine `readr` is more flexible on some of those, like handling various datetime formats etc. but in general listed operations seems to be working in DT already
```r
> str(fread(text="a,b\nz,x\n", stringsAsFactors=TRUE))
Classes 'data.table' and 'data.frame':	1 obs. of  2 variables:
$ a: Factor w/ 1 level "z": 1
$ b: Factor w/ 1 level "x": 1
> str(fread(text="a,b\nz,x\n", colClass=c("character","factor")))
Classes 'data.table' and 'data.frame':	1 obs. of  2 variables:
$ a: chr "z"
$ b: Factor w/ 1 level "x": 1
> str(fread(text="a,b\nz,2011-09-03\n"))
Classes 'data.table' and 'data.frame':	1 obs. of  2 variables:
$ a: chr "z"
$ b: IDate, format: "2011-09-03"
> str(fread(text="a,b\nz,2020-05-01T03:14:18.343Z\n"))
Classes 'data.table' and 'data.frame':	1 obs. of  2 variables:
$ a: chr …
```
=> update fread parser info

NEWS.md
Currently, it's not rendered as a code block. Two more spaces are needed here.
=> Fix some indents of NEWS.md

R/collectors.R, man/parse_datetime.Rd
It seems this part of the doc is now broken. Maybe this is forgotten to be unescaped when migrated to markdown format?
https://readr.tidyverse.org/reference/parse_datetime.html#format-specification:
=> Fix escaping of % on col_date()/col_datetime()'s doc

DESCRIPTION
since readr uses `is_present()` https://github.com/r-lib/lifecycle/blob/master/NEWS.md#lifecycle-020
=> Add minimal lifecycle version

R/read_delim_chunked.R, man/read_delim_chunked.Rd
Add a detail to the `read_delim_chunked` documentation indicating that the number of lines in file can exceed R's MAX_INT value, per this [commit](https://github.com/tidyverse/readr/commit/c3169d0470bd570d8915b8212b6b00e6ad5594d9).
=> Add detail to documentation of `read_delim_chunked`

R/collectors.R
When using explicit LaTeX-like "itemize" and "enumerate" environments, special characters require escaping. Currently, the documentation for collectors does *not* escape its special characters. This leads to issues such as the following:
This commit addresses this issue by instead using Markdown within documentation blocks. This has been tested locally by building the documentation with `pkgdown::build_site()` and verifying that "parse_datetime.html" was rendered in the expected way. The screenshot below illustrates the output.
=> Fixes collectors documentation (e.g. parse_date).

tests/testthat/test-read-lines.R
`expect_warning()` and `expect_message()` will now return the conditions instead of the value, consistently with `expect_error()`.
We're planning to release end of this week, see https://github.com/r-lib/testthat/issues/1454. A patch release would be great :)
=> Compatibility with dev testthat

R/melt_delim.R, R/melt_fwf.R, R/melt_table.R, man/melt_delim.Rd, man/melt_fwf.Rd, man/melt_table.Rd
For convenience of users wanting to jump straight to the package. I ran the Document button in RStudio that ultimately runs `devtools::document(roclets = c('rd', 'collate', 'namespace'))` and only committed the relevant changes to this PR. Open to feedback and other changes.
=> Add meltr link to documentation

NEWS.md, R/read_delim.R, R/read_delim_chunked.R, R/read_log.R, R/read_table.R, R/utils.R, man/read_delim_chunked.Rd, man/read_log.Rd, man/read_table.Rd, man/should_show_types.Rd, man/spec_delim.Rd, tests/testthat/_snaps/edition-1/col-spec.md, tests/testthat/_snaps/edition-2/col-spec.md, tests/testthat/setup.R, tests/testthat/test-col-spec.R
`read_table()` is one of the functions that currently doesn't have a
vroom equivalent, so is still using the first edition parser. When we
added support for `show_col_types` we didn't port that back to the first
edition parser, so it was missing in `read_table()` and the
`read_delim_chunked()` functions.
Fixes #1331
=> Add support for show_col_types for edition 1 parser

DESCRIPTION
`variant=` argument of `expect_snapshot` was added then:
https://github.com/tidyverse/readr/blob/5a098243c026edb46d8c1cbb2f9f3a69297aac10/tests/testthat/test-read-csv.R#L233
=> Add a version dependency on testthat

DESCRIPTION, NEWS.md, R/date-symbols.R, R/locale.R, R/read_builtin.R, R/utils.R, R/zzz.R, tests/testthat/_snaps/utils.md, tests/testthat/test-utils.R
This is in reponse to a request from CRAN.
Previously this expectation:
```
expect_error(read_builtin(AirPassengers, "datasets"))
```
would call `utils::data()` on malformed input, i.e. intentionally calling with the symbol `AirPassengers`. Eventually that lead to some condition having length greater than 1. So we got an error, alright, but an error that indicates a programming problem.
I think this means `utils::data()` might have an input-checking problem, but it's not my problem.
Instead, I'll be more careful to catch obviously bad input in readr itself.
I was able to reproduce what CRAN reported with released R (they used R-devel) with env var settings such as:
```
_R_CHECK_LENGTH_1_CONDITION_=verbose
_R_CHECK_LENGTH_1_CONDITION_="abort,verbose"
```
Note that "true" is not enough to …
=> Check read_builtin()'s inputs

R/collectors.R, man/parse_factor.Rd
Recent factor work made me realize some of the docs around factor handling were confusing or ambiguous. This PR is meant to tighten things up.
vroom inherits the relevant parameter documentation from readr, so this basically covers both packages.
=> Improve docs for `parse_factor()` / `col_factor()`

tests/testthat/test-write.R
When we made the changes necessary for https://github.com/tidyverse/vroom/pull/436 this caused test failures in readr that are outdated since we are no longer quoting `NA`s
Because `readr::format_csv()` uses `vroom::vroom_format()` the tests for https://github.com/tidyverse/vroom/pull/436 I think should stay there rather than also being in readr.
=> Update test for `NA` quoting

R/read_delim.R, man/read_delim.Rd, man/read_fwf.Rd, man/spec_delim.Rd
Fixes #1421
Add examples for `col_select` in readr since we currently don't have any.
=> Add examples for `col_select` and remove mention of `list()`

R/collectors.R, man/parse_number.Rd
Fixes #1424
Developed from #1415
Tightening up the docs for how `parse_number()` would parse a string that contains valid numbers and non-numeric characters. Specifically, to detail this situation, where `parse_number()` only parses the first number it finds:
```r
readr::parse_number("132aa000")
#> [1] 132
```
=> Clarify docs for parse number

R/read_delim.R, man/read_delim.Rd, man/read_delim_chunked.Rd, man/read_fwf.Rd, man/read_log.Rd, man/read_table.Rd, man/spec_delim.Rd
So "By default, reading a" is no longer nested within the bulleted list
=> Correct doc indenting

README.Rmd, README.md
I propose to add `read_csv2()` to the README. 
I haven't committed the README.md re-render, because it contains quite a few whitespace changes.
=> add `read_csv2()` to README

R/read_delim.R, man/read_delim.Rd, man/read_delim_chunked.Rd, man/read_fwf.Rd, man/read_log.Rd, man/read_table.Rd, man/spec_delim.Rd
This PR adds a missing backtick and re-documents to get proper code styling
=> Fix typo in docs
